package thesimpleems_16nov;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.Arrays;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author P0068839
 */
public class MainJFrame extends javax.swing.JFrame {
    
    // ATTRIBUTES
    public MyHashTable theHT;
    
    
    // CONSTRUCTORS
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        theHT = new MyHashTable(10);
        System.out.println("HERE HERE");
        
    }
    
    
    // METHODS   
    
    public MyHashTable getTheHT() {
        return theHT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jButton5.setText("Save all employees to file");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Create three employees, add to hash table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Display all of the employees in the hash table");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add new employee");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressed_jButton3(evt);
            }
        });

        jButton6.setText("Load all employees from file");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton4.setText("Display info for a single employee");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Save all employees to file");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Remove employee");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Edit info for a single employee");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addComponent(jButton6))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton8)
                            .addComponent(jButton9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton6)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       
        FTE theFTE;
        PTE thePTE;
        
        theFTE = new FTE(111111, "Elmer", "Fudd", "Male", "Mississauga", 0.2, 80000.00);
        theHT.addEmployee(theFTE);
        System.out.println("Added the FTE to the hash table!");
                
        thePTE = new PTE(222222, "Daffy", "Duck", "Male", "Mississauga", 0.22, 10.0, 20.0, 30.0);
        theHT.addEmployee(thePTE);
        System.out.println("Added the PTE to the hash table!");
                
        theFTE = new FTE(333333, "Lola", "Bunny", "Female", "Mississauga", 0.17, 90000.00);
        theHT.addEmployee(theFTE);
        System.out.println("Added the FTE to the hash table!");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        SeparateJFrame theSeparateJFrame = new SeparateJFrame();
        theSeparateJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        theSeparateJFrame.setMainHT(refVal);  // Have theSeparateJFrame mainHT point to the real HT.
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pressed_jButton3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressed_jButton3
        // TODO add your handling code here:
        AddNewEmployeeJFrame theANEJFrame = new AddNewEmployeeJFrame();
        theANEJFrame.setVisible(true);
        theANEJFrame.setPreferredSize(new Dimension(810, 810));
        MyHashTable refVal = getTheHT();
        theANEJFrame.setMainHT(refVal);
    }//GEN-LAST:event_pressed_jButton3

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        // Here, I need code that walks through the entire hash table
        // and writes the attribute values for each employee to a
        // text file (by using say buffered writer).
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        // Here, I need code that reads the attribute values for the employee
        // data stored in a text file (by say using buffered reader) and adding
        // each of those employees to the hash table.
        try {
            Scanner sc = new Scanner(new FileReader("EmployeeStorage.txt"));
            
            
            String line = null;
            String[] values;
            
            while(sc.hasNextLine()){
                line = sc.nextLine();
                values = line.split("\\|"); // splits with |
                for(int i=0; i<values.length; i++)  {
                    values[i] = values[i].replaceAll("!@!", "\\|");
                }
                try{
                    if(values[0].equals("FTE")){

                        int theEmpNum = Integer.parseInt(values[1]);
                        String theFirstName = values[2];
                        String theLastName = values[3];
                        String gender = values[4];
                        String workLoc = values[5];
                        
                        double deductRate = Double.parseDouble(values[6]);

                        FTE theFTE;

                        double yearlySalary = Double.parseDouble(values[7]);
                        theFTE = new FTE(theEmpNum, theFirstName, theLastName,
                                    gender, workLoc, deductRate, yearlySalary);
                        theHT.addEmployee(theFTE);

                    }else if(values[0].equals("PTE")){

                        int theEmpNum = Integer.parseInt(values[1]);
                        String theFirstName = values[2];
                        String theLastName = values[3];
                        String gender = values[4];
                        String workLoc = values[5];
                        
                        double deductRate = Double.parseDouble(values[6]);

                        PTE thePTE;

                        double hourlyWage = Double.parseDouble(values[7]);
                        double hoursPerWeek = Double.parseDouble(values[8]);
                        double weeksPerYear = Double.parseDouble(values[9]);

                        thePTE = new PTE(theEmpNum, theFirstName, theLastName, gender,
                        workLoc, deductRate, hourlyWage, hoursPerWeek, weeksPerYear);
                        theHT.addEmployee(thePTE);
                                                
                    }


                }catch(Exception e){
                    continue;
                }
            }
        } catch (FileNotFoundException ex) {
            System.err.println("File Not Found!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DisplayEmployeeJFrame theDisplayEmployeeJFrame = new DisplayEmployeeJFrame();
        theDisplayEmployeeJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        theDisplayEmployeeJFrame.setMainHT(refVal);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         // TODO add your handling code here:
        
        // Here, I need code that walks through the entire hash table
        // and writes the attribute values for each employee to a
        // text file (by using say buffered writer).
        try {
                FileWriter inputFile = new FileWriter("EmployeeStorage.txt", false);
                inputFile.write("");
                inputFile.flush();
                inputFile.close();
                FileWriter rewriter = new FileWriter("EmployeeStorage.txt", true);
                for (int i = 0; i < theHT.buckets.length; i++) {
                    for (int j = 0; j < theHT.buckets[i].size(); j++) {
                        EmployeeInfo emp = theHT.buckets[i].get(j);
                        
                        if (emp instanceof FTE) {
                            emp.firstName = emp.firstName.replaceAll("\\|", "!@!");
                            emp.lastName = emp.lastName.replaceAll("\\|", "!@!");
                            rewriter.write("FTE|" + emp.empNum + "|" + emp.firstName + "|" + emp.lastName + "|" +
                                emp.gender + "|" + emp.workLoc + "|" + emp.deductRate + "|" + ((FTE) emp).getYearlySalary() + "\n");
                        }
                        else if(emp instanceof PTE){
                        emp.firstName = emp.firstName.replaceAll("\\|", "!@!");
                        emp.lastName = emp.lastName.replaceAll("\\|", "!@!");
                        rewriter.write("PTE|" + emp.empNum + "|" + emp.firstName + "|" + emp.lastName + "|" +
                                emp.gender + "|" + emp.workLoc + "|" + emp.deductRate + "|" + ((PTE) emp).getHourlyWage() +
                                "|" + ((PTE) emp).getHoursPerWeek() + "|" + ((PTE) emp).getWeeksPerYear() + "\n");
                    }
                        
                    }
                }
                rewriter.flush();
                rewriter.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        RemoveEmployeeJFrame theRemoveEmployeeJFrame = new RemoveEmployeeJFrame();
        theRemoveEmployeeJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        theRemoveEmployeeJFrame.setMainHT(refVal);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        EditEmployeeJFrame theEditEmployeeJFrame = new EditEmployeeJFrame();
        theEditEmployeeJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        theEditEmployeeJFrame.setMainHT(refVal);
    }//GEN-LAST:event_jButton9ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
